### ISSUE TITLE
Source code repo for `esutils` is not present / get rid of `esutils`

### ISSUE THREAD

**Issue by KOLANICH** [0o120/escodegen-python#1]
1. https://pypi.org/project/esutils/ claims that the source is https://github.com/0o120/esutils-python , but 

>Page not found

2. The functions within the source code files within wheel look like
a. implemented suboptimally for a Python impl
b. some of them should belong to other packages.

Also you may want to take a look at https://github.com/UniGrammar/escapelib.py and https://github.com/UniGrammar/charRanges.py that contain some infrastructure that may be useful for your quest

**Comment by 0o120** [comment]
Fixed. Repo was set on private. Set to public.
